#!/bin/bash -

i=0
cat $1 | while read line ; do
let i+=1
echo "cd $PWD/$line$2"
echo "cp ../processLanePairedGTFParam ../$3 ./"
echo "./processLanePairedGTFParam "$line"_1.fasta.gz "$line"_2.fasta.gz $line$2 $3 $4$i $5 $6 $7 $8"
echo "pwd"
done
