#!/bin/bash

cp $3 Parameters1.in

echo '#!/bin/bash' > $4
echo  "/home/sharmaa4/TOOLS/STAR-2.7.3a/bin/Linux_x86_64_static/STAR --runMode alignReads --runThreadN " $8 " --outFileNamePrefix " $2 " --outStd Log --genomeDir " $5 " --readFilesIn "$6$1 " --parametersFiles Parameters1.in" >> $4

chmod a+x $4
qsub -q 256gb.q,all.q,matlab.q,sandbox.q -cwd -o $PWD -e $PWD -M sharmaa4@cshs.org -m bea -l $7 -pe mpich $8 ./$4
